### ISSUE TITLE
FR: add support for __declspec(noreturn)

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#136]
Another "not a big priority, but still would be nice someday": Add support for `__declspec(noreturn)`.

The GCC `__attribute__ ((noreturn))` may be implemented along with this or separately, I'm referencing it here because it does exactly the same (GCC attributes in general are tracked under #96):

```c
extern void	my_abort (const char *, const int)	__attribute__((noreturn));		// GCC variant
__declspec(noreturn)	extern void	my_abort (const char *, const int);		// Supported by MSC since years
```

This *may* have an effect for the optimizer, too, but from the user side it is primary useful for compiler diagnostics like this one:

```c
int
somefunc (const int stuff)
{
	switch (stuff) {
	case 1:
		return 100;
	case 2:
		return 3000;
	case 3:
		return 50000;
	/* LCOV_EXCL_START */
	default:
		printf ("unexpected stuff: %d"), stuff);
		my_abort ((__FILE__, __LINE__));
	/* LCOV_EXCL_STOP */
	}
}
```

~~~
;============ Compiling test.c ============
Warning(105)  C:\dev\test.c(123):  Function should return a value in function somefunc

Compile done.  Errors: 0,  Warnings: 1
~~~

**Comment by GitMensch** [comment]
Doesn't seem to work.

```c
__declspec(noreturn) __declspec(dllexport) extern void	cob_stop_run	(const int);
```
results in
> Warning(482)  X:\gnucobol\libcob/common.h(1856):  Missing type specifier for identifier 'noreturn'
> Error( 11)    X:\gnucobol\libcob\libcob/common.h(1856):  Syntax error: ; expected

**Comment by GitMensch** [comment]
@LADSoft Rechecked with 

> occ Version 6.0.37.1 Copyright (C) LADSoft 2006-2018
> Compile date: May 20 2018, time: 15:47:09

Still the same issue:

> Warning(482) X:\gnucobol\libcob/common.h(1856): Missing type specifier for identifier 'noreturn'
> Error( 11) X:\gnucobol\libcob\libcob/common.h(1856): Syntax error: ; expected

Please reopen...

**Comment by LADSoft** [comment]
I'm not seeing it.  I put this in a file by itself:

> __declspec(noreturn) __declspec(dllexport) extern void	cob_stop_run	(const int);

And it compiles fine on the  most recent CI build.   I also tried compiling common.h and couldn't duplicate the issue

I will fix the other compatibility issues though.

**Comment by LADSoft** [comment]
problem was __declspec is defined as a macro in the headers.   I'm undefining it and this issue should be fixed.

**Comment by GitMensch** [comment]
Current status: compiling with `__declspec(noreturn)` works, but the warning 105 is still raised when the last statement of the function is a call to a function defined with this attribute.

**Comment by GitMensch** [comment]
I still get the warnings in these cases... Did you tested for the expected result (in this case we'd have to dig deeper)? Note: if build from within OCIDE you should be able to reproduce it with #168, which should compile without this warning ;-)

**Comment by LADSoft** [comment]
yeah I tested with #168...   it initially didn't seem to work but then I remember you had told me to go into a header file and enable it (by adding __ORANGEC__ to the list of things that declared the associated macro properly).   Once I did that maybe ten warnings went away, and when I looked through the error list I couldn't see those warnings any more...   I had definitely seen them before.   Let me know if it is still a problem and I will retest again...

**Comment by GitMensch** [comment]
Sorry for the rant, all fine with the provided testbed (I have more than one on more than one pc...), the message is suppressed and as the other testbed showed - only where specified.
All is fine with this issue.
