### ISSUE TITLE
release request

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#389]
Of course, this is just to be seen as a suggestion. My personal "relevant issues" would be:

#369
#376  
#386
#387 

and, for something old:
#63 (at least started)

Background: most of these have a "will be done next" hint and once these are finished we'll likely already have more than 100 commits since the last change (and, along with all the nice things fixed in the meantime we'll also have the first OCCIL integrated release + the first OCCIL update since nearly 2 years).

Maybe it would be a good time to start using the milestones?

**Comment by LADSoft** [comment]
We'll see about #63...   I realized after the first build failed last night there are a lot of new compiler warnings with the newly added codebase, same kind of stuff as was in the code I already fixed, I was going to prioritize fixing them pretty high (before I mark #369 complete).  The others sure some of them are already in process:)

I'm just hoping that the chocolately install for inno setup works the way I want it to with the new version so we can still do artifacts on appveyor...

**Comment by LADSoft** [comment]
I made a milestone...   that was kinda interesting :smile:

**Comment by GitMensch** [comment]
Closed in favor of the actual [milestone](https://github.com/LADSoft/OrangeC/milestone/1). Let's see if #63 still gets some time before the release.
