### ISSUE TITLE
Using std::cref results in an error

### ISSUE THREAD

**Issue by tenk-a** [LADSoft/OrangeC#48]
Using std::cref results in an error
smp.cpp:
```
#include <functional>
#include <cassert>
int main() {
    int n = 11;
    //auto rwn = std::ref(n);   // ok
    auto rwn = std::cref(n);    // error
    assert(rwn.get() == 11);
    n = 22;
    assert(rwn.get() == 22);
}
```
RESULT:
Error(232)    C:\Program Files (x86)\Orange C 386\include\__functional_base(480):  Could not find a match for 'std::__1::reference_wrapper<_Tp>::reference_wrapper<_Tp>(reference_wrapper<int>)' in function std::__1::cref<int>( const int&)
Warning(436)  smp.cpp(6):  In template instantiation started here

**Comment by tenk-a** [comment]
I compiled smp.cpp with 6.0.31.1

However, it is not "auto", writing a type name seems to be an error.
```
#include <functional>
#include <cassert>
int main() {
    int n = 11;
    //std::reference_wrapper<int>     rwn = std::ref(n);    // ok
    std::reference_wrapper<int const> rwn = std::cref(n);   // error
    assert(rwn.get() == 11);
    n = 22;
    assert(rwn.get() == 22);
}
```
RESULT:
```
Error(232)    smp2.cpp(6):  Could not find a match for 'std::__1::reference_wrapper<int>::reference_wrapper<int>(reference_wrapper<_Tp>)' in function main
```

**Comment by LADSoft** [comment]
fixed

**Comment by tenk-a** [comment]
I compiled with v 6.0.32.1.
Thank you.

**Comment by tenk-a** [comment]
There was still an error
```
#include <functional>
#include <cassert>
int main() {
    int n = 11;
    std::reference_wrapper<int>	rwn = std::ref(n);
    n = 10;
    assert(rwn == 10);
    std::reference_wrapper<int const> crwn = std::cref(n);
    n = 12;
    assert(crwn == 12);
}
```
Error(232)    smp3.cpp(10):  Could not find a match for 'operator ==(std::__1::reference_wrapper<int>, int)' in function main

**Comment by LADSoft** [comment]
sorry for the long delay.   It should be fixed now though.

**Comment by tenk-a** [comment]
I compiled with v 6.0.33.1.
Thank you.
